package com.example.demo.ussd.enums;

public enum UssdMenuState {
    MAIN_MENU,
    BALANCE_INQUIRY,
    MINI_STATEMENT,
    LOAN_APPLICATION,
    LOAN_PRODUCTS,
    LOAN_AMOUNT_INPUT,
    LOAN_TERM_INPUT,
    DEPOSIT_MENU,
    DEPOSIT_AMOUNT_INPUT,
    MPESA_DEPOSIT,
    BANK_TRANSFER,
    PIN_VERIFICATION,
    CHANGE_PIN_MENU,
    OLD_PIN_INPUT,
    NEW_PIN_INPUT,
    CONFIRM_PIN_INPUT,
    TRANSACTION_CONFIRMATION,
    PROCESSING
}
